INSERT INTO "acronyms" ("acronym", "meaning") VALUES
('A&A', 'Amniocentesis and abortion'),
('AA', 'American Atheists'),
('AAA', 'Americans Against Abortion'),
('AAA', 'American Adoption Agency'),
('AAAS', 'American Association for the Advancement of Science'),
('AACP', 'American Academy of Child Psychiatry'),
('AAD', 'Alliance Against Defamation'),
('AAFP', 'American Academy of Family Physicians'),
('AAHA', 'American Academy of Health Administration'),
('AAHS', 'Americans Against Human Suffering'),
('AAI', 'Alternatives to Abortion International'),
('AAL', 'American Abolitionist League'),
('AAMCH', 'American Association of Maternal & Child Health'),
('AAME', 'American Academy of Medical Ethics'),
('AAMFT', 'American Association for Marriage and Family Therapy'),
('AANFP', 'American Academy of Natural Family Planning'),
('AANP', 'American Academy of Nurse Practitioners'),
('AANS', 'American Academy of Neurological Surgeons'),
('AAP', 'American Academy of Pediatrics'),
('AAR', 'American Academy of Religion'),
('AARP', 'American Association of Retired Persons'),
('AAS', 'American Association of Suicidology'),
('AAS', 'Abortion Abolition Society'),
('AASECT', 'American Association of Sex Educators, Counselors and Therapists'),
('AASK', 'Aid to Adoption of Special Kids'),
('AATB', 'American Association of Tissue Banks'),
('AAUN', 'American Association of the United Nations'),
('AAUW', 'American Association of University Women'),
('ABA', 'American BooksellersAssociation'),
('ABA', 'American Bar Association'),
('ABC', 'American Baby Code'),
('ABC', 'American Broadcasting Company'),
('AB', 'American Birth Control League'),
('ABEDA', 'Arab Bank for Economic Development in Africa'),
('ABM', 'Anti-ballistic missile'),
('ABMS', 'American Board of Medical Specialties'),
('ABOG', 'American Board of Obstetrics and Gynecology'),
('Abp', 'Archbishop'),
('ABS', 'American Bible Society'),
('ACA', 'Americans for a Constitutional Amendment'),
('ACA', 'Americans for Constitutional Action'),
('ACA', 'Arms Control Association'),
('ACC', 'Arab Cooperation Council'),
('ACCL', 'American Citizens Concerned for Life'),
('ACCT', 'Agence de Cooperation Culturelle et Technique'),
('TC', 'Technical Cooperation'),
('ACE', 'Alliance for Chastity Education'),
('ACE', 'American Council on Education'),
('ACF', 'Americans for Constitutional Freedom'),
('ACGME', 'Accreditation Council for Graduate Medical Education'),
('ACHR', 'American Convention on Human Rights'),
('ACL', 'American Collegians for Life'),
('ACLA', 'American Catholic Lawyers Association'),
('ACLU', 'American Civil Liberties Union'),
('ACNM', 'American College of Nurse-Midwives'),
('ACOG', 'American College of Obstetrics and Gynecology'),
('ACOOG', 'American College of Osteopathic Obstetricians and Gynecologists'),
('ACOP', 'American College of Osteopathic Pediatricians'),
('ACP', 'American College of Physicians'),
('ACP', 'African, Caribbean, and Pacific Countries'),
('ACS', 'Americans for Common Sense'),
('ACS', 'American College of Surgeons'),
('ACT-UP', 'AIDS Coalition to Unleash Power'),
('ACTH', 'Adrenocorticotropic hormone'),
('ACW', 'Action for World Community'),
('AD', 'Anno Domini'),
('ADA', 'Americans for Democratic Action'),
('ADA', 'Adenosine deaminase'),
('ADL', 'Anti-Defamation League [of Bnai Brith]'),
('ADRDAA', 'Alzheimers Disease and Related Disorders Association'),
('AE', 'Artificial embryonation'),
('AE', 'American Education Association'),
('AEA', 'Adoption Exchange Program'),
('AEC', 'Atomic Energy Commission'),
('AED', 'Academy for Educational Development'),
('AEI', 'American Enterprise Institute'),
('AELC', 'Association of Evangelical Lutheran Churches'),
('AEU', 'American Ethical Union'),
('AFA', 'American Family Association'),
('AFAM', 'Ancient Free and Accepted Masons'),
('AFC', 'Apostolate for Family Consecration'),
('AfDB', 'African Development Bank'),
('AFDC', 'American Family Defense Coalition'),
('AFDC', 'Aid for Families with Dependent Children'),
('AFE', 'Americans for the Environment'),
('AFESD', 'Arab Fund for Economic and Social Development'),
('AFGE', 'American Federation of Government Employees'),
('AFJ', 'Alliance for Justice'),
('AFL-CIO', 'American Federation of Labor and Congress of Industrial Organizations'),
('AFL', 'Adolescent Family Life'),
('AFLM', 'Advocates for Life Ministries'),
('AFMCH', 'American Foundation for Maternal and Child Health'),
('AFP', '[Maternal] alpha-feto protein'),
('AFS', 'American Fertility Society'),
('AFSC', 'American Friends Service Committee'),
('AFSCME', 'American Federation of State, County, and Municipal Employees',),
('AFT', 'American Federation of Teachers'),
('AG', 'Attorney general'),
('AG', 'Andean Group'),
('AGA', 'Alliance of Gay Artists'),
('AGA', 'American Gay Atheists'),
('AGA', 'American Genetic Association'),
('AGI', 'Alan Guttmacher Institute'),
('AGP', 'Association of Gay Psychologists'),
('AGPA', 'American Group Psychotherapy Association'),
('AGS', 'American Geriatrics Society'),
('AGS', 'American Gynecological Society'),
('AHA', 'American Hospital Association'),
('AHA', 'American Humane Association'),
('AHA', 'American Historical Association'),
('AHA', 'American Humanist Association'),
('AHEA', 'American Home Economics Association'),
('AI', 'Amnesty International'),
('AI', 'Artificial insemination'),
('AI', 'Artificial intelligence'),
('AIAA', 'Americans for International Aid and Adoption'),
('AID', 'Artificial insemination'),
('AID', '[United States] Agency for International Development'),
('AIDS', 'Acquired Immune Deficiency Syndrome'),
('AIFR', 'American Institute of Family Relations'),
('AIH', 'Artificial insemination'),
('AIHCA', 'American Indian Health Care Association'),
('AIM', 'Accuracy in Media'),
('AIM', 'American Indian Movement'),
('AIPOP', 'American Institute of Public Opinion Poll'),
('AIR-PLUS', 'American Information Route Toward a Pro-Life United States'),
('AISA', 'Adoption Information Service Agency'),
('AIUM', 'American Institute of Ultrasound in Medicine'),
('AJC', 'American Jewish Congress'),
('AJOG', 'American Journal of Obstetrics and Gynecology'),
('AKA', 'Also known as'),
('AL', 'Arab League'),
('ALA', 'American Library Association'),
('ALADI', 'Asociacion Latinoamericana de Integracion'),
('IA', 'Integration Association'),
('ALC', 'American Lutheran Church'),
('ALD', 'Adrenoleukodystrophy'),
('ALEC', 'American Legislative Exchange Council'),
('ALERT', 'American Life Education and Research Trust'),
('ALF', 'Animal Liberation Front'),
('ALG', 'American Lawyers Guild'),
('ALI', 'American Law Institute'),
('ALI', 'American Liberties Institute'),
('ALL', 'American Life League'),
('ALL', 'American Life Lobby'),
('ALMA', 'Adoptees Liberty Movement Association'),
('ALS', 'Amyotrophic lateral sclerosis'),
('ALSE', 'Advocates for Gay and Lesbian State Employees'),
('AMA', 'American Medical Association'),
('AMEN', 'AIDS in Multi-Ethnic Neighborhoods Study'),
('AMEND', 'Moms Experiencing Neonatal Death'),
('AMF', 'Arab Monetary Fund'),
('AMFAR', 'American Foundation for AIDS Research'),
('AMOS', 'Assumptions are the mother of all screwups'),
('AMU', 'Arab Maghreb Union'),
('AMWA', 'American Medical Womens Association'),
('ANA', 'American Nurses Association'),
('ANC', 'African National Congress'),
('ANM', 'Auxiliary nurse-midwife'),
('ANZUS', 'Australia-New Zealand-United States Security Treaty'),
('AOA', 'American Orthopsychiatric Association'),
('AOG', 'Assembly of God'),
('AOH', 'Ancient Order of Hibernians'),
('AORN', 'American Association of Registered Nurses'),
('AP', 'Associated Press'),
('APA', 'American Psychoanalytic Association'),
('APA', 'American Psychiatric Association'),
('APA', 'American Pharmaceutical Association'),
('APA', 'American Psychological Association'),
('APC', 'American Parents Committee'),
('APCW', 'Adolescent Pregnancy Childwatch Project'),
('APEC', 'Asia Pacific Economic Cooperation'),
('APHA', 'American Public Health Association'),
('APHA', 'American Protestant Hospital Association'),
('APL', 'Adopted People for Life'),
('APLIC', 'Association for Population/Family Planning and Information Centers'),
('APO', 'Army Post Office'),
('APPP', 'Association of Planned Parenthood Physicians'),
('APS', 'Artificial placentation system'),
('APSH', 'Association for Persons with Severe Handicaps'),
('APTN', 'American Public Television Network'),
('APWU', 'American Postal Workers Union'),
('ARAC', 'Animal Rights Activists for Choice'),
('ARAL', 'Association to Repeal Abortion Laws'),
('ARC', 'American Red Cross'),
('ARC', 'AIDS-Related Complex'),
('ARF', 'Animal Rights Front'),
('ARHO', 'Association of Reproductive Health Officials'),
('ARHP', 'Association of Reproductive Health Professionals'),
('ARL', 'Americans for Religious Liberty'),
('ARM', 'Abortion Rights Mobilization'),
('ARMS', 'Abortion-Related Ministries'),
('ARP', 'Association for Retarded Persons'),
('ARSC', 'Abortion Survivors Rescue Committee'),
('ARV', 'AIDS-related virus'),
('ASA', 'Association for the Study of Abortion'),
('ASA', 'American Sociological Association'),
('ASAHP', 'Association of Schools of Allied Health Professions'),
('ASAP', 'As soon as possible'),
('ASAT', 'Anti-satellite weapons'),
('ASC', 'American Security Council'),
('ASCAP', 'American Society of Composers, Authors and Publishers'),
('AsDB', 'Asian Development Bank'),
('ASEAN', 'Association of Southeast Asian Nations'),
('ASF', 'American Suicide Foundation'),
('ASHA', 'American Social Health Association'),
('ASHG', 'American Society of Human Genetics'),
('ASHS', 'Association of Secular Humanist Societies'),
('ASLM', 'American Society of Law and Medicine'),
('ASM', 'American Society of Mammologists'),
('ASMA', 'American Student Medical Association'),
('ASPEN', 'American Society for Parenteral and Enteral Nutrition'),
('ASRC', 'Abortion Survivors Rescue Committee'),
('AT&T', 'Atlantic Telephone and Telegraph'),
('ATCC', 'American Type [Cell] Culture Collection'),
('ATL', 'Association of Trial Lawyers'),
('ATP', 'Adenosine triphosphate'),
('AU', 'Angstrom unit'),
('AUL', 'Americans United for Life'),
('AUSCS', 'Americans United for Separation of Church and State'),
('AVA', 'American Victims of Abortion'),
('AVC', 'American Veterans Committee'),
('AVDA', 'American Venereal Disease Association'),
('AVDP', 'Avoirdupois'),
('AVES', 'Australian Voluntary Euthanasia Society'),
('AVS', 'Association for Voluntary Sterilization'),
('AWMA', 'American Womens Medical Association'),
('AWOL', 'Absent without leave'),
('AZT', 'Azidothymidine'),
('BA', 'Bachelor of Arts'),
('BACAOR', 'Bay Area Coalition Against Operation Rescue'),
('BAD', 'Banque Africaine de Developpement [African Development Bank'),
('BADEA', 'Banque Arabe de Developpement Economique en Afrique'),
('BATF', 'Bureau of Alcohol, Tobacco and Firearms'),
('BB/BSA', 'Big Brothers/Big Sisters of America'),
('BBA', 'Balanced Budget Amendment'),
('BBB', 'Better Business Bureau'),
('BBC', 'British Broadcasting Corporation'),
('BBT', 'Basal body temperature'),
('BCFA', 'Birth Control Federation of America'),
('BCIE', 'Banco Centroamericano de Integracion Economico'),
('BEI', 'Bank for Economic Integration'),
('BCR', 'Benefit-cost ratio'),
('BCS', 'Bethany Christian Services'),
('BD', 'Bachelor of Divinity'),
('BDEAC', 'Banque de Developpment des Etats de lAfrique Centrale'),
('ASDB', 'African States Development Bank'),
('BIDS', 'Birth Defects Information System'),
('BEU', 'Benelux Economic Union'),
('BGCS', 'Boyhood Gender Conformity Scale'),
('BID', 'Banco Interamericano de Desarrollo'),
('BIP', 'Basic infertile pattern'),
('BIRTH', 'Born Individuals Rescuing the Helpless'),
('BIS', 'Bank for International Settlements'),
('BM', 'Basal metabolism'),
('BMA', 'British Medical Association'),
('BOAD', 'Banque Ouest-Africaine de Developpement'),
('BOHICA', 'Bend over here it comes again!'),
('BOM', 'Billings Ovulation Method'),
('BORN', 'Bi-State Operation Rescue Network'),
('BPOE', 'Benevolent and Protective Order of Elks'),
('BS', 'Bachelor of Science'),
('BSA', 'Boy Scouts of America'),
('BSCS', 'Biological Sciences Curriculum Study'),
('BSEC', 'Black Sea Economic Cooperation Zone'),
('BVM', 'Blessed Virgin Mother'),
('BWMT', 'Black and White Men Together'),
('BWS', 'Better World Society'),
('C', 'Commonwealth'),
('C-PLAN', 'Communist Party Legislative Action Network'),
('C', '[Degrees] Celsius'),
('C-Span', 'Congressional Coverage Cable Network'),
('CAC', 'Christian Action Council'),
('CACM', 'Central American Common Market'),
('CAEU', 'Council of Arab Economic Unity'),
('CAH', 'Congenital adrenal hyperplasia'),
('CAHEA', 'Committee on Allied Health Education and Accreditation'),
('CALC', 'Clergy & Laity Concerned'),
('CALM', 'Custody Action for Lesbian Mothers'),
('CAMPUS', 'Coalition of American Pro-Life University Students'),
('CAN', 'Cult Awareness Network'),
('CAP', 'Children Awaiting Parents'),
('CAP', 'Committee for American Principles'),
('CAPD', 'Continuous ambulatory peritoneal dialysis'),
('CARAL', 'California Abortion Rights Action League'),
('CARAL', 'Canadian Abortion Rights Action League'),
('CARD', 'Committee Against Registration and the Draft'),
('CARE', 'Co-operative for American Remittances to Everywhere'),
('CARE', 'Counseling for Abortion-Related Experiences'),
('CARICOM', 'Caribbean Community and Common Market'),
('CARR', 'Coalition Against the Radical Right'),
('CASE', 'Christian Advocates Serving Evangelism'),
('CBA', 'Christian Booksellers Association'),
('CBC', 'Congressional Black Caucus'),
('CBC', 'Canadian Broadcasting Corporation'),
('CBE', 'Center for Biomedical Ethics'),
('CBPP', 'Center for Budget and Policy Priorities'),
('CBS', 'Columbia Broadcasting System'),
('CBSS', 'Council of the Baltic Sea States'),
('CBTV', 'Coalition for Better Television'),
('CCA', 'Christian Community Association'),
('CCAR', 'Central Conference of American Rabbis'),
('CCBA', 'Coalition of Concerned Black Americans'),
('CCC', 'Customs Cooperation Council'),
('CCCB', 'Canadian Conference of Catholic Bishops'),
('CCD', 'Confraternity of Christian Doctrine'),
('CCEL', 'Christian Civic Education League'),
('CCF', 'Cooperative Commonwealth Federation'),
('CCL', 'Conference for Catholic Lesbians'),
('CCL', 'Couple to Couple League'),
('CCPA', 'Catholics for Christian Political Action'),
('CCR', 'Center for Constitutional Rights'),
('CCR', 'Citizens for Congressional Reform'),
('CCREF', 'Conservative Caucus Research and Education Fund'),
('CCS', 'Clergy Consultation Service'),
('CD', 'Congressional district'),
('CDA', 'Catholic Daughters of America'),
('CDB', 'Caribbean Development Bank'),
('CDC', 'Centers for Disease Control'),
('CDF', 'Childrens Defense Fund'),
('CDI', 'Center for Defense Information'),
('CDL', 'Citizens for Decency Through Law'),
('CDRR', 'Committee for the Defense of Reproductive Rights'),
('CE', '[International Society of] Christian Endeavor'),
('CE', 'Council of Europe'),
('CEAO', 'Communaute Economique de lAfrique de lOuest'),
('EC', 'Economic Community'),
('CED', 'Committee for Economic Development'),
('CEDPA', 'Centre for Development and Population Activities'),
('CEEAC', 'Communaute Economique des Etats de lAfrique Centrale'),
('CCAS', 'Community of Central African States'),
('CEI', 'Central European Initiative'),
('CEIP', 'Carnegie Endowment for National Peace'),
('CEMA', 'Council for Mutual Economic Assistance'),
('CEO', 'Chief executive officer'),
('CEP', 'Council on Economic Priorities'),
('CEP', 'Council on Environmental Quality'),
('CEPGL', 'Communaute Economique des Pays des Grands Lacs'),
('CGLC', 'Community of the Great Lakes Countries'),
('CERES', 'Center for Research in Education and Sexuality'),
('CERN', 'Conseil Europeen pour la Recherche Nucleaire'),
('CNR', 'Center for Nuclear Research'),
('CETA', 'Comprehensive Employment and Training Act'),
('CFA', 'Committee for Future America'),
('CFC', 'Chlorofluourocarbons'),
('CFC', 'Combined Federal Campaign'),
('CFD', 'Concern for Dying'),
('CFFC', 'Catholicsfor a Free Choice'),
('CFR', 'Code of Federal Regulations'),
('CG', 'Contadora Group'),
('CGD', 'Chronic granulomatous disease'),
('CHA', 'Catholic Health Association'),
('CHA', 'Christian Holiness Association'),
('CHAMPUS', 'Civilian Health and Medical Program of the Uniformed Services'),
('CHAMPVA', 'Civilian Health and Medical Program of the Veterans Administration'),
('CHAP', 'Child Health Assurance Program'),
('CHAUS', 'Catholic Health Association of the United States'),
('CHCE', 'Center for Health Care Ethics'),
('CHD', 'Campaign for Human Development'),
('CHEER', 'Center for Homosexual Education, Evaluation and Research'),
('CHILD', 'Christians Helping in Lifes Defense'),
('CHOICE', 'Concern for Health Options, Information, Care and Education'),
('CHSA', 'Consumer Health Service of America'),
('CIA', 'Central Intelligence Agency'),
('CICRED', 'Committee for International Cooperation in National Research in'),
('CID', 'Criminal Investigation Department'),
('CIDA', 'Canadian International Development Agency'),
('CIF', 'Conservation International Foundation'),
('CIN', 'Cervical intraepithelial neoplasia'),
('CIOMS', 'Council for International Organizations of Medical Sciences'),
('CIS', 'Center for Inter-American Security'),
('CISPES', 'Committee in Solidarity With the People of El Salvador'),
('CISS', 'Chromosomal in-situ suppression hybridization'),
('CIV', 'Cultures, ideas and values [course]'),
('CJ', 'Chief Justice'),
('CJR', 'Citizens for Judicial Restraint'),
('CLC', 'Campaign Life Coalition'),
('CLC', 'Clergy and Laity Concerned'),
('Clear-TV', 'Christian Leaders for Responsible Television'),
('CLF', 'Conservation Law Foundation'),
('CLRCR', 'Catholic League for Religious and Civil Rights'),
('CLS', 'Critical Legal Studies'),
('CLS', 'Christian Legal Society'),
('CLW', 'Council for a Livable World'),
('CM', 'Calendar method'),
('CM', 'Congregation for the Mission'),
('CM-BBT', 'Cervical Mucus-Basal Body Temperature'),
('CMA', 'Catholics for a Moral America'),
('CMAC', 'Catholic Marriage Advisory Council'),
('CMEA', 'Council for Mutual Economic Assistance'),
('CMF', 'Cardinal Mindszenty Foundation'),
('CMA', 'Canadian Medical Association'),
('CN-M', 'Certified nurse-midwife'),
('CNF', 'Conservation Network Foundation'),
('CNN', 'Cable News Network'),
('CNS', 'Central nervous system'),
('CNS', 'Committee for National Security'),
('CO', 'Conscientious objector'),
('CODEL', 'Coordination in Development'),
('COMECON', 'Coordinating Committee on Export Controls'),
('CCC', 'Con-Con Constitutional Convention'),
('CONRAD', 'Contraceptive Research and Development Program, Eastern Virginia'),
('MS', 'Medical School'),
('CONUS', 'Continental United States'),
('COPE', 'Committee on Political Education'),
('COR', 'Coalition on Revival'),
('CORE', 'Congress of Racial Equality'),
('COYOTE', 'Cast Off Your Old Tired Ethics'),
('CP', 'Colombo Plan'),
('CP', 'Congregation of the Passion'),
('CP', 'Communist Party'),
('CPA', 'Certified public accountant'),
('CPA', 'Center for Policy Alternatives'),
('CPB', 'Corporation for Public Broadcasting'),
('CPC', 'Crisis Pregnancy Center'),
('CPE', 'Council on Population and Environment'),
('CPF', 'Committee to Protect the Family'),
('CPFH', 'Center for Population and Family Health, Columbia University'),
('CPG', 'Catholic Physicians Guild'),
('CPG', 'Catholic Pharmaceutical Guild'),
('CPGAF', 'Committee on Population Growth and the American Family'),
('CPM', 'Cesarian Prevention Movement'),
('CPS', 'Contraceptive Prevalence Surveys'),
('CPS', 'Current Population Surveys'),
('CPUSA', 'Communist Party of the United States of America'),
('CR', 'Calendar rhythm'),
('CRA', 'Center for Reproductive Alternatives'),
('CRASH', 'Center for Reproductive and Sexual Health'),
('CRASH', 'Committee Against Racism, sexism, and Heterosexism'),
('CREOG', 'Council on Resident Education in Obstetrics and Gynecology'),
('CRF', 'Constitutional Rights Foundation'),
('CRLP', 'Center for Reproductive Law and Policy'),
('CRTI', 'Center for the Rights of the Terminally Ill'),
('CRW', 'Council of Religious Women'),
('CS', 'Christian Science'),
('CSC', 'Civil Service Commission'),
('CSC', 'Congregatio Sanctae Crucis'),
('CSCE', 'Conference on Security and Cooperation in Europe'),
('CSCPA', 'Committee for Social Change and Political Action'),
('CSE', 'Classroom sex education system'),
('CSER', 'Committee for the Scientific Examination of Religion'),
('CSFC', 'Committee for the Survival of a Free Congress'),
('CSII', 'Continuous subcutaneous insulin infusion'),
('CSOW', 'Commission on the Status of Women'),
('CSP', 'Center for Security Policy'),
('CSSP', 'Center for Studies of Suicide Prevention'),
('CSsR', 'Congregatio Sanctissimi Redemptoris'),
('CT', 'Certified teacher'),
('CTFA', 'Cosmetic, Toiletry, and Fragrance Association'),
('CTS', 'Catholic Truth Society'),
('CTSA', 'Catholic Theological Society of America'),
('CTW', 'Childrens Television Network'),
('CU', 'Consumers Union'),
('CUA', 'Catholic University of America'),
('CUDESH', 'Council for Democratic and Secular Humanism'),
('CUF', 'Catholics United for the Faith'),
('CUL', 'Catholics United for Life'),
('CULT', 'Catholics United Against Liberation Theology'),
('CURE', 'Citizens United for Responsible Education'),
('CURE', 'Citizens United Resisting Euthanasia'),
('CUSA', 'Cavitron ultrasonic surgical aspirator'),
('CUT', 'Church Universal and Triumphant'),
('CVS', 'Chorionic Villi Sampling'),
('CW', 'Conventional wisdom'),
('CWA', 'Concerned Women for America'),
('CWLA', 'Child Welfare League of America'),
('CWRR', 'Catholic Women for Reproductive Rights'),
('CWU', 'Church Women United'),
('CYO', 'Catholic Youth Organization'),
('D.A.', 'District attorney'),
('D&C', 'Dilatation and curettage'),
('D&E', 'Dilatation and evacuation'),
('DACOWITS', 'Defense Advisory Committee on Women in the Services'),
('DAD', 'Dads Against Discrimination'),
('DAP', 'Dial-a-porn'),
('DAR', 'Daughters of the American Revolution'),
('DARE', 'Drug Abuse Resistance Education'),
('DARE', 'Dykes Against Racism Everywhere'),
('DAV', 'Disabled American Veterans'),
('DBP', 'Defense Budget Project'),
('DC', 'Developed country'),
('DC', 'District of Columbia'),
('DC', 'Doctor of Chiropractic'),
('DCL', 'Doctor of Canon Law'),
('DD', 'Doctor of Divinity'),
('DDC', 'Dewey Decimal Classification'),
('DEIS', 'Draft environmental impact statement'),
('DES', 'Diethylstilbestrol'),
('DFA', 'Development Fund for Africa'),
('DG', 'Dei Gratia'),
('DHEW', 'Department of Health, Education, and Welfare'),
('DHHS', 'Department of Health and Human Services'),
('DHS', 'Demographic and Health Surveys'),
('DHS', 'Demographic and Health Surveys'),
('DHT', 'Dihydrotestosterone'),
('DINK', 'Double-income, no kids'),
('DLC', 'Democratic Leadership Council'),
('DM', 'Deutsche Mark'),
('DMPA', 'Depot-medroxyprogesterone acetate'),
('DNA', 'Deoxyribonucleic acid'),
('DNC', 'Democratic National Committee'),
('DNR', 'Do not resuscitate'),
('DoD', 'Department of Defense'),
('DOM', 'Deo optimo maximo'),
('DORIS', 'Defending Our Rights in the Streets'),
('DPA', 'Durable power of attorney'),
('DRG', 'Diagnosis-related group'),
('DSI', 'Development Services International of Canada'),
('DSM', 'Diagnostic and Statistical Manual'),
('DSOC', 'Democratic Socialist Organizing Committee'),
('DSP', 'Daughters of St. Paul'),
('DSS', 'Delayed Shock Syndrome'),
('DV', 'Douay Version'),
('DV', 'Deo volente'),
('e.g.', 'Exempli gratia'),
('EAB', 'Ethics advisory board'),
('EADB', 'East African Development Bank'),
('EAF', 'Environmental Action Foundation'),
('EBRD', 'European Bank for Reconstruction and Development'),
('EC', 'European Community'),
('EC', 'Evangelicals Concerned'),
('ECA', 'Economic Commission for Africa'),
('ECAFE', 'Economic Commission for Asia and the Far East'),
('CAP', 'Commission for Asia and the Pacific'),
('ECE', 'Economic Commission for Europe'),
('ECG', 'Electrocardiogram'),
('ECLA', 'Economic Commission for Latin America'),
('LAC', 'Latin America and the Caribbean '),
('ECLAC', 'Economic Commission for Latin America and the Caribbean'),
('ECMO', 'Extracorporeal membrane oxygenation'),
('ECO', 'Economic Cooperation Organization'),
('ECOSOC', 'Economic and Social Council'),
('ECOSOC', '[United Nations] Economic and Social Council'),
('ECOWAS', 'Economic Community of West African States'),
('ECWA', 'Economic Commission for Western Asia'),
('CWA', 'Commission for Western Asia'),
('EDF', 'Environmental Defense Fund'),
('EDT', 'Eastern daylight time'),
('EE', 'Engaged Encounter'),
('EE2', 'Ethinyl estradiol'),
('EEC', 'European Economic Community'),
('EEC', 'Euthanasia Educational Council'),
('EEG', 'Electroencephalogram'),
('EEOC', 'Equal Employment Opportunity Commission'),
('EFM', 'Electronic fetal monitoring'),
('EFTA', 'European Free Trade Association'),
('EGF', 'Epidermal growth factor'),
('EI', 'Eosinophilic index'),
('EIB', 'European Investment Bank'),
('EIB', 'Excellence in Broadcasting [Network]'),
('EIFT', 'Embryo intrafallopian transfer'),
('EIS', 'Environmental impact statement'),
('EKG', 'Electrocardiogram'),
('ELCA', 'Evangelical Lutheran Church in America'),
('ELI', 'Environmental Law Institute'),
('ELISA', 'Enzyme-linked immunosorbent assay'),
('EMILY', 'Early Money is Like Yeast'),
('EMP', 'Electromagnetic pulse'),
('ENTA', 'Norethindrone acetate'),
('EO', 'Executive Order'),
('EPA', 'Environmental Protection Agency'),
('EPC', 'Environmental Policy Center'),
('EPH', 'Edema/proteinuria/hypertension'),
('EPK&C', 'Early prenatal karyotype farenand cell scan'),
('EPS', 'Early Pregnancy Services'),
('ERC', 'Ethical Research Committee'),
('ERIS', 'Exoatmospheric Reentry Intercept System'),
('ESA', 'European Space Agency'),
('ESCAP', 'Economic and Social Commission for Asia and the Pacific'),
('ESCWA', 'Economic and Social Commission for Western Asia'),
('ESF', 'Economic support funds'),
('ESMP', 'Enhanced survival of multifetal pregnancy'),
('EST', '[Werner] Erhardt Sensitivity Training Seminars'),
('EST', 'Eastern standard time'),
('et seq', 'Et sequens'),
('ET', 'Embryo transfer'),
('ETA', 'Estimated time of arrival'),
('ETO', 'Estimated time of ovulation'),
('EWTN', 'Eternal Word Television Network'),
('F', '[Degrees] Fahrenheit'),
('FA', 'Fundamentalists Anonymous'),
('FAA', 'Federal Aviation Administration'),
('FAA', 'Foreign Assistance Act'),
('FACE', 'Freedom of Access to Clinic Entrances [Act]'),
('FACES', 'National Association for the Craniofacially Handicapped'),
('FACOG', 'Fellow, American College of Obstetrics and Gynecology'),
('FACP', 'Fellow of the American College of Physicians'),
('FACS', 'Flourescence-activated cell sorter'),
('FACS', 'Fellow of the American College of Surgeons'),
('FAM', 'Fertility awareness method'),
('FAO', 'Food and Agricultural Organization'),
('FARM', 'Farm Animal Reform Movement'),
('FAS', 'Fetal alcohol syndrome'),
('FAS', 'Federation of American Scientists'),
('FBI', 'Federal Bureau of Investigation'),
('FCA', 'Fellowship of Christian Athletes'),
('FCAA', 'Florence Crittenden Association of America'),
('FCC', 'Freedom of Choice Coalition'),
('FCC', 'Federal Council of Churches'),
('FCC', 'Federal Communications Commission'),
('FCF', 'Free Congress Foundation'),
('FCI', 'Family Care International, Inc.'),
('FDA', '[United States] Food and Drug Administration'),
('FEBS', 'Federation of European Biochemical Societies'),
('FEC', 'Federal Elections Commission'),
('FEHB', 'Federal Employees Health Benefits'),
('FEMALE', 'Formerly Employed Mothers at Loose Ends'),
('FEW', 'Federally Employed Women'),
('FFLA', 'Feminists for Life of America'),
('FFM', 'Fund for a Feminist Majority'),
('FFP', 'Friends of Family Planning'),
('FHA', 'Federal Housing Administration'),
('FHA', 'Future Homemakers of America'),
('FHI', 'Family Health International'),
('FIAMC', 'International Federation of Catholic Medical Associations'),
('FINRRAGE', 'Feminist International Network of Resistance to Reproductive and Genetic'),
('E', 'Engineering'),
('FISH', 'Fluorescent in-situ hybridization'),
('FLE', 'Family Life Education'),
('FLS', 'Front Line States'),
('FOA', 'Field operating activity'),
('FOCA', 'Freedom of Choice Act'),
('FOE', 'Friends of the Earth'),
('FOE', 'Fraternal Order of Eagles'),
('FOI', 'Freedom of Information [Act]'),
('FOLKS', 'Friends of Little Kids'),
('FOR', 'Fellowship of Reconciliation'),
('FPA', 'Family planning associates'),
('FPA', 'Family Protection Act'),
('FPIA', 'Family Planning International Assistance Program'),
('FPWA', 'Federation of Protestant Welfare Agencies'),
('FRC', 'Family Research Council'),
('FRCP', 'Fellow of the Royal College of Physicians, London'),
('FRCS', 'Fellow of the Royal College of Surgeons, London'),
('FRG', 'Federal Republic of Germany'),
('FRI', 'Family Research Institute'),
('FSA', 'Family Service Association'),
('FSA', 'Free Speech Advocates'),
('FSH', 'Follicle-stimulating hormone'),
('FSP', 'Fallopian tube sperm perfusion'),
('FTA-Abs', 'Fluorescent treponemal antibody-absorption'),
('FUAA', 'Fathers United Against Abortion'),
('FUBAR', 'Fouled up beyond all recognition'),
('FWHC', 'Feminist Womens Health Center'),
('FY', 'Fiscal year'),
('FYI', 'For your information'),
('FZ', 'Franc Zone'),
('G-77', 'Group of 77'),
('G', 'Grand'),
('G7', 'Group of Seven'),
('GALA', 'Gay and Lesbian Alliance'),
('GALA', 'Gay Atheists League of America'),
('GALAS', 'Great American Lesbian Art Show'),
('GAMDA', 'Group Against Media Dishonesty on Abortion'),
('GAO', 'General Accounting Office'),
('GAP', 'Gay Awareness Program'),
('GAS', 'Gay Alliance of Students'),
('GATT', 'General Agreement on Tariffs and Trade'),
('GAU', 'Gay Academic Union'),
('GB', 'Gigabyte'),
('GBS', 'Gay bowel syndrome'),
('GCC', 'Gulf Cooperation Council'),
('GCC', 'Gay Community Center'),
('GDABM', 'Global Defense Against Ballistic Missiles'),
('GDP', 'Genome Data Base'),
('GDR', 'German Democratic Republic'),
('GEA', 'Gay Educators Association'),
('GEEP', 'Gonadotropin-releasing hormone agonist and exogenous estradiol and'),
('GFC', 'Gay Fathers Coalition'),
('GFWC', 'General Federation of Womens Clubs'),
('GHOST', 'Grand Homosexual Organization to Stop Televangelists'),
('GI', 'Government issue'),
('GI', 'Girls Incorporated'),
('GIFT', 'Gamete intra-fallopian transfer'),
('GLAAD', 'Gay and Lesbian Alliance Against Defamation'),
('GLAD', 'Gay and Lesbian Awareness Day'),
('GLF', 'Gay Liberation Front'),
('GLSA', 'Gay Law Students Association'),
('GM-CSF', 'Granulocyte-macrophage colony-stimulating factor'),
('GMA', 'Gay Militant Atheists'),
('GMC', 'General Medical Council'),
('GNP', 'Gross national product'),
('GnRH', 'Gonadotrophin-releasing hormone'),
('GnRHa', 'Gonadotrophin-releasing hormone agonist'),
('GnRHa', 'Gonadotrophin-releasing-hormone analogue'),
('GOA', 'Government Accounting Office'),
('GOBs', 'Good old boys'),
('GOMER', 'Get out of my emergency room'),
('GOP', 'Grand Old Party'),
('GORK', 'God only really knows'),
('GP', 'General practitioner'),
('GPA', 'Grade-point average'),
('GPHW', 'Gay Public Health Workers'),
('GPO', '[United States] Government Printing Office'),
('GRID', 'Gay-Related Immune Deficiency'),
('GRINCH', 'Gay Retaliation for Inexcusable Negligence and Criminal Homophobia'),
('GRNC', 'Gay Rights National Lobby'),
('GSA', 'Genetics Society of America'),
('GSA', 'Girl Scouts of America'),
('GSA', 'General Services Administration'),
('GSA', 'Gay Students Association'),
('GTA', 'Gay Theatre Alliance'),
('GTA', 'Gay Teachers Association'),
('GTC', 'Global Tomorrow Coalition, Inc.'),
('GTC', 'Gay Teachers Coalition'),
('GTW', 'Multiglycosides of Tripterygium wilfordii'),
('GUM', 'Great unwashed masses'),
('H.B.', 'House Bill'),
('H.J.R.', 'House Joint Resolution'),
('HATTS', 'Hemagglutination treponemal test for syphilis'),
('HC', 'House of Commons'),
('HC', 'Holy Communion'),
('HCFA', 'Health Care Financing Administration'),
('HCG', 'Human chorionic gonadotrophin'),
('HCS', 'Human chorionic somatomammotropin'),
('HD', 'Huntingtons disease'),
('HDDA', 'Humane and Dignified Death Act'),
('HDL', 'High-density lipoprotein'),
('HEW', '[United States Department of] Health, Education and Welfare'),
('HGP', 'Human Genome Project'),
('HHH', 'Hyperornithinaemia, Hyperammonaemia, and Homocitrullinuria Syndrome'),
('HHS', '[United States Department of] Health and Human Services'),
('HIRE', 'Hooking is Respectable Employment'),
('HIT', 'Herd of independent thinkers [syndrome]'),
('HIV', 'Human immunodeficiency virus'),
('HIV-Ag', 'Human immunodeficiency virus antigen'),
('HL', 'House of Lords'),
('HLA', 'Human Life Amendment'),
('HLB', 'Human Life Bill'),
('HLC', 'Human Life Center'),
('HLF', 'Human Life Foundation'),
('HLI', 'Human Life International'),
('HLS', 'Human Life Statute'),
('HLSC', 'Human Life Statute Coalition'),
('HM', 'His or Her Majesty'),
('HMG', 'Human menopausal gonadotrophin'),
('HMO', 'Health maintenance organization'),
('HOPE', 'Housing Opportunities for People Everywhere'),
('HOPING', 'Helping in Normal Grieving'),
('HOW', 'Happiness of Womanhood'),
('HQ', 'Headquarters'),
('HRH', 'His or Her Royal Highness'),
('HRT', 'Hormone replacement therapy'),
('HSA', 'Health Systems Agencies'),
('HSG', 'Hysterosalpingogram'),
('HSLDA', 'Home School Legal Defense Association'),
('HTLV', 'Human T-Cell Lymphotropic Virus'),
('HUGO', 'Human Genome Organization'),
('HV', 'Humanae Vitae'),
('HZA', 'Hemizona assay'),
('IADB', 'Inter-American Development Bank'),
('IAEA', 'International Atomic Energy Agency'),
('IAETF', 'International Anti-Euthanasia Task Force'),
('IASR', 'International Academy of Sex Research'),
('IAWS', 'Intercollegiate Association of Women Students'),
('IBEC', 'International Bank for Economic Cooperation'),
('IBM', 'International Business Machine'),
('IBRC', 'Infant Bioethical Review Committee'),
('IBRD', 'International Bank for Reconstruction and Development'),
('ICAM-1', 'Intercellular adhesion molecule-1'),
('ICAO', 'International Civil Aviation Organization'),
('ICASC', 'International Contraception, Abortion, and Sterilization Campaign'),
('ICBM', 'Intercontinental ballistic missile'),
('ICC', 'International Chamber of Commerce'),
('ICC', 'Interstate Commerce Commission'),
('ICCC', 'International Concerns Committee for Children'),
('ICCR', 'Interfaith Center on Corporate Responsibility'),
('ICD', 'Intracervical device'),
('ICEA', 'International Childbirth Education Association'),
('ICEM', 'Intergovernmental Committee for European Migration'),
('IOM', 'International Organization for Migration'),
('ICFTU', 'International Confederation of Free Trade Unions'),
('ICGI', 'International Conference on Gender Identity'),
('ICJ', 'International Court of Justice'),
('ICJ', 'International Court of Justice'),
('ICM', 'Intergovernmental Committee for Migration'),
('ICOMP', 'International Council on Management of Population Programmes'),
('ICRC', 'International Committee of the Red Cross'),
('ICS', 'Institute for Creation Spirituality'),
('ICU', 'Intensive care unit'),
('IDA', 'International Development Association'),
('IDB', 'Islamic Development Bank'),
('IDDS', 'Institute for Defense & Disarmament Studies'),
('IEA', 'International Energy Agency'),
('IEC', 'Institutional ethics committee'),
('IEP', 'Inhibin-enriched preparation'),
('IERA', 'Inclusive Equal Rights Amendment'),
('IF', 'Intellectual Freedom'),
('IFA', 'International Fertility Association'),
('IFAD', 'International Fund for Agricultural Development'),
('IFC', 'International Finance Corporation'),
('IFCA', 'International Federation of Catholic Alumnae'),
('IFFLP', 'International Federation for Family Life Promotion'),
('IFFS', 'International Federation of Fertility Societies'),
('IFGR', 'International Foundation for Genetic Research'),
('IFN', 'Interferon'),
('IFRP', 'International Fertility Research Program'),
('IGA', 'International Gay Association'),
('IGAB', 'Interagency Group for Action on Breastfeeding'),
('IGADD', 'Inter-Governmental Authority on Drought and Development'),
('IGF', 'Insulin-like growth factor'),
('IHM', '[Servants of the] Immaculate Heart of Mary'),
('IHS', 'Indian Health Service'),
('IIB', 'International Investment Bank'),
('IIE', 'Institute of International Education'),
('IIED', 'International Institute for Environment and Development'),
('iiFAR', 'Incurably Ill for Animal Research'),
('IISHR', 'International Institution for the Study of Human Reproduction'),
('ILGWU', 'International LadiesGarment WorkersUnion'),
('ILO', 'International Labor Organization'),
('ILO0', 'International Labor Organization'),
('ILS', 'International Life Services'),
('IMAP', '[International Planned Parenthood Federation] Medical Advisory Board'),
('IMCO', 'Intergovernmental Maritime Consultative Organization'),
('IMO', 'International Maritime Organization'),
('IME', 'Institute of Medical Ethics'),
('IMF', 'International Monetary Fund'),
('IMO', 'International Maritime Organization'),
('IMP', 'Imprimatur'),
('IMPACT', 'Innovative Materials for Population Action'),
('InCAR', 'International Committee Against Racism'),
('INFACT', 'Infant Formula Coalition'),
('INMARSAT', 'International Maritime Satellite Organization'),
('INPLAN', 'Integrated Population and Development Planning'),
('INRI', 'Iesus Nazarenus Rex Iudaeorum'),
('INS', 'Immigration and Naturalization Service'),
('INSERM', 'Institut National de la Sant:e et de la Recherche Medicale'),
('INTELSAT', 'International Telecommunications Satellite Organization'),
('INTERPOL', 'International Criminal Police Organization'),
('INTRAH', '[Program for] International Training in Health, University of North'),
('IOC', 'International Olympic Committee'),
('IOM', 'International Organization for Migration'),
('IOOF', 'International Order of Odd Fellows'),
('IPA', 'International Phonetic Alphabet'),
('IPAS', 'International Projects Assistance Services'),
('IPPF', 'International Planned Parenthood Federation'),
('IPS', 'Institute for Policy Studies'),
('IR', 'International Review'),
('FP', 'Family Planning'),
('IRBM', 'Intermediate Range Ballistic Missile'),
('IRC', 'Interchange Resource Network'),
('IRCAR', 'International Reference Center for Abortion Research'),
('IRD', 'Institute for Resource Development, Westinghouse'),
('IRLF', 'International Right to Life Foundation'),
('IRNFP', 'International Review of Natural Family Planning'),
('IRS', 'Internal Revenue Service'),
('IRTLF', 'International Right to Life Federation'),
('ISIS', 'Institute for the Scientific Investigation of Sexuality'),
('ISO', 'International Organization for Standardization'),
('ISTI', 'International Science and Technology Institute, Inc.'),
('ITEST', 'Institute for Theological Encounter With Science and Technology'),
('ITOP', 'Induced termination of pregnancy'),
('ITU', 'International Telecommunication Union'),
('IUB', 'Intrauterine occlusion body'),
('IUCD', 'Intra-uterine contraceptive device'),
('IUD', 'Intra-uterine device'),
('IUI', 'Intra-uterine insemination'),
('IUP', 'Intrauterine pregnancy'),
('IUSSP', 'International Union for the Scientific Study of Population'),
('IV', 'Intravenous'),
('IVD', 'Intravas device'),
('IVF-DS', 'IVF-donor sperm'),
('IVF-SET', 'IVF-surrogate embryo transfer'),
('IVF-DO', 'IVF-donor ova'),
('IVF-DE', 'IVF-donor embryo'),
('IVF', 'In-vitro fertilization'),
('IVH', 'Intraventricular hemorrhage'),
('IVIG', 'Intravenous immunoglobulin'),
('IWHC', 'International Womens Health Coalition'),
('IWO', 'Institute for World Order'),
('IWW', 'Industrial Workers of the World'),
('IWY', 'International Womens Year'),
('IYC', 'International Year of the Child'),
('IYD', 'International Year of the Disabled'),
('JACGUAR', 'Johns and Call Girls United Against Repression'),
('JAMA', 'Journal of the American Medical Association'),
('JBS', 'John Birch Society'),
('JCAH', 'Joint Commission on the Accreditation of Hospitals'),
('JCB', 'Bachelor of Canon Law'),
('JCHA', 'Joint Committee of Hospital Associations'),
('JCL', 'Licentiate in Canon Law'),
('JD', 'Juris Doctor'),
('JDL', 'Jewish Defense League'),
('JHPIEGO', 'Johns Hopkins Program for International Education in Gynecology and'),
('JLC', 'Juvenile Law Center'),
('JLIC', 'Jewish Life Issues Committee'),
('JOICFP', 'Japanese Organization for International Cooperation in Family Planning,'),
('JP', 'Justice of the Peace'),
('JPSA', 'Joint Program for the Study of Abortion'),
('JS&A', 'John Short & Associates, Inc.'),
('JSD', 'Doctor of Juristic Science'),
('JSI', 'John Snow, Inc.'),
('JW', 'Jehovahs Witness'),
('K of P', 'Knights of Pythias'),
('K of C', 'Knights of Columbus'),
('kB', 'Kilobyte'),
('KI', 'Karyopyknotic index'),
('KIA', 'Killed in action'),
('KISS', 'Keep it simple, stupid'),
('KJV', 'King James Version'),
('KKK', 'Ku Klux Klan'),
('KROW', 'Keep Rockefeller out of Washington'),
('KS', 'Kaposis Sarcoma'),
('KTF', 'Keep the Faith'),
('L/GHTS', 'Lesbian and Gay Humanists'),
('L.A.', 'Latin America'),
('LAAL', 'Life After [sexual] Assault League'),
('LABIA', 'Lesbians and Bisexuals in Action'),
('LAES', 'Latin American Economic System'),
('LAIA', 'Latin American Integration Association'),
('LAPAC', 'Life Amendment Political Action Committee'),
('LAPD', 'Los Angeles Police Department'),
('LARFPC', 'Los Angeles Regional Family Planning Council'),
('LAS', 'League of Arab States'),
('LAV', 'Lymphadenopathy Virus'),
('LAW', 'Legal Action for Women'),
('LC-WS', 'Lutheran Church-Wisconsin Synod'),
('LC-MS', 'Lutheran Church-Missouri Synod'),
('LC', 'Library of Congress'),
('LCD', 'Lowest common denominator'),
('LCL', 'League of Catholic Laymen'),
('LD50', 'Lethal Dose 50%'),
('LDC', 'Less-developed country'),
('LDL', 'Low-density lipoprotein'),
('LDS', 'Latter-Day Saints'),
('LEAD', 'League for Economic Assistance and Development'),
('LH', 'Luteinizing hormone'),
('LIFE', 'Life Issues in Formal Education'),
('LII', 'Life Issues Institute'),
('LLB', 'Bachelor of Law'),
('LLD', 'Doctor of Law'),
('LLDC', 'Least developed country'),
('LLLI', 'La Leche League International'),
('LLM', 'Master of Law'),
('LNG', 'Levonorgestrel'),
('LNMP', 'Last normal menstrual period'),
('LOOM', 'Loyal Order of Moose'),
('LORCS', 'League of Red Cross and Red Crescent Societies'),
('LRF', 'Luteinizing releasing factor'),
('LSC', 'Legal Services Corporation'),
('LSMT', 'Life-sustaining medical treatment'),
('LTL', 'Laparoscopic tubal ligation'),
('LTOT', 'Low tube ovum transfer'),
('LWV', 'League of Women Voters'),
('MA', 'Master of Arts'),
('MACS', 'Multicenter AIDS Cohort Study'),
('MAD', 'Mutual assured destruction'),
('MAIDS', 'Murine [mouse] Acquired Immune Deficiency Syndrome'),
('MAMA', 'Mothers Against Minors Abortions'),
('MAP', 'More Agricultural Production, Inc.'),
('MAR', 'Mixed antiglobulin reaction'),
('MB', 'Megabyte'),
('MBA', 'Master of Business Administration'),
('MBS', 'Mutual Broadcasting System'),
('MC', 'Member of Congress'),
('MCAD', 'Medium-chain acyl-CoA dehydrogenase deficiency'),
('MCC', 'Metropolitan Community Church'),
('MCCL', 'Minnesota Citizens Concerned for Life'),
('MCH', '[Department of] Maternal and Child Health'),
('MCHR', 'Medical Committee for Human Rights'),
('MD', 'Medical doctor'),
('MDA', 'Muscular dystrophy association'),
('ME', 'Menstrual extraction'),
('ME', 'Medical examiner'),
('ME', 'Marriage Encounter'),
('MEP', 'Multiple exposure photography'),
('MERCOSUR', 'Mercado Comun del Cono Sur'),
('MeSH', 'Medical subject headings'),
('MFS', 'Mobilization for Survival'),
('MG', 'Myasthenia Gravis'),
('MHD', 'Magnetohydrodynamics'),
('MIA', 'Missing in action'),
('MIC', 'Maternal and Infant Care'),
('MICU', 'Medical intensive care unit'),
('MIM', 'Morality in Media'),
('MINURSO', 'United Nations Mission for the Referendum in Western Sahara'),
('MIRV', 'Multiple independently-targeted reentry vehicles'),
('MIT', 'Massachusetts Institute of Technology'),
('MM', 'Maryknoll Missioners'),
('MM', 'Moral Majority'),
('MoD', 'March of Dimes'),
('MOM', 'Mothers Organized for Morality'),
('MP', 'Member of Parliament'),
('MPA', 'Medroxyprogesterone acetate'),
('MPA', 'Master of Public Administration'),
('MPH', 'Master of Public Health'),
('MPS', 'Mucopolysaccharidoses'),
('MS', 'Master of Science'),
('MS', 'Multiple sclerosis'),
('Msgr', 'Monsignor'),
('MSH', 'Management Sciences for Health'),
('MSI', 'Marie Stopes International'),
('MSSVD', 'Medical Society for the Study of Venereal Diseases'),
('MSW', 'Master of Social Work'),
('MTCR', 'Missile Technology Control Regime'),
('MWA', 'Modern Woodmen of America'),
('MX', 'Missile, experimental'),
('MYOB', 'Mind your own business'),
('NAACP', 'National Association for the Advancement of Colored People'),
('NAAF', 'National Association for Abortion Facilities'),
('NAAO', 'National Association of Artists Organizations'),
('NAAPC', 'National Association for the Advancement of Preborn Children'),
('NAB', 'National Association of Broadcasters'),
('NAC', 'Network Action Committee'),
('NACAC', 'North American Council on Adoptable Children'),
('NACC', 'North Atlantic Cooperation Council'),
('NACHO', 'North American Conference of Homophile Organizations'),
('NACHRI', 'National Association of Childrens Hospitals and Associated Institutions'),
('NAE', 'National Association of Evangelicals'),
('NAF', 'National Abortion Federation'),
('NAGAP', 'National Association of Gay Alcoholism Professionals'),
('NAJSN', 'National American Jewish Students Network'),
('NAM', 'Nonaligned Movement'),
('NAM', 'New American Movement'),
('NAM', 'New age movement'),
('NAMBLA', 'North American Man-Boy Love Association'),
('NANN', 'National Association of Neonatal Nurses'),
('NAOP', 'National Association for Optional Parenthood'),
('NAPARE', 'National Association for Perinatal Addiction, Research, and Education'),
('NAPN', 'National Association of Pro-Life Nurses'),
('NAPSAC', 'National Association of Parents and Professionals for Safe Alternatives in'),
('CB', 'Childbirth'),
('NAPWA', 'National Association of People with AIDS'),
('NARAL', 'National Abortion Rights Action League [formerly the National'),
('NARAL', 'National Association for the Repeal of Abortion Laws'),
('NARHC', 'National Association of Reproductive Health Centers'),
('NARRAL', 'National Abortion and Reproductive Rights Action League'),
('ARAL', 'Association for the Repeal of Abortion Laws'),
('NARW', 'National Assembly of Religious Women'),
('NAS', 'National Audobon Society'),
('NAS', 'National Association of Scholars'),
('NASSP', 'National Association of Secondary School Principals'),
('NASW', 'National Association of Social Workers'),
('NATO', 'North Atlantic Treaty Organization'),
('NAWL', 'National Association of Women Lawyers'),
('NBAU', 'No business as usual'),
('NBC', 'National Broadcasting Company'),
('NBFO', 'National Black Feminists Organization'),
('NBPTS', 'National Board for Professional Teaching Standards'),
('NBWHP', 'National Black Womens Health Project'),
('NC', 'Nordic Council'),
('NCA', 'National Committee for Adoption'),
('NCA', 'National Chastity Association'),
('NCAC', 'National Coalition Against Censorship'),
('NCADP', 'National Coalition to Abolish the Death Penalty'),
('NCADV', 'National Coalition Against Domestic Violence'),
('NCAN', 'National Coalition of American Nuns'),
('NCAP', 'National Community AIDS Partnership'),
('NCC', 'National Council of Churches'),
('NCC', 'National Catholic Coalition'),
('NCCB', 'National Council of Catholic Bishops'),
('NCCC', 'National Coalition of Clergy and Laity'),
('NCCC', 'National Council of Catholic Charities'),
('NCCJ', 'National Conference of Christians and Jews'),
('NCCL', 'National Committee of Catholic Laymen'),
('NCCW', 'National Council of Catholic Women'),
('NCCY', 'National Committee for Children and Youth'),
('NCDC', 'National Catholic Development Conference'),
('NCE', 'New Catholic Edition'),
('NCEA', 'National Catholic Education Association'),
('NCFA', 'National Committee for Adoption'),
('NCFPI', 'National Clearinghouse for Family Planning Information'),
('NCFR', 'National Council on Family Relations'),
('NCGLC', 'National Coalition of Gay and Lesbian Counselors'),
('NCGO', 'National Coalition of Gay Organizations'),
('NCGSTDS', 'National Coalition of Gay Sexually-Transmitted Disease Services'),
('NCHA', 'National Council on Higher Education'),
('NCHLA', 'National Committee for a Human Life Amendment'),
('NCHS', 'National Center for Health Statistics'),
('NCI', 'National Cancer Institute'),
('NCJW', 'National Council of Jewish Women'),
('NCLR', 'National Center for Lesbian Rights'),
('NCNW', 'National Council of Negro Women'),
('NCOG', 'National Council of Obstetrics and Gynecology'),
('NCPAC', 'National Conservative Political Action Committee'),
('NCSW', 'National Conference on Social Welfare'),
('NCTE', 'National Council of Teachers of English'),
('NCWUS', 'National Council of Women of the United States'),
('NDA', 'New drug application'),
('NDA', 'Natural Death Act'),
('NEA', 'Nuclear Energy Agency'),
('NEA', 'National Endowment for the Arts'),
('NEA', 'National Education Association'),
('NEC', 'National Ecumenical Coalition'),
('NECLU', 'National Emergency Civil Liberties Committee'),
('NEET', 'Nafarelin European Endometriosis Trial Group'),
('NEH', 'National Endowment for the Humanities'),
('NEJM', 'New England Journal of Medicine'),
('NEN', 'Norethindrone acetate'),
('NEP', 'New Economic Policy'),
('NERPRC', 'New England Regional Primate Research Center'),
('NET', 'Norethindrone'),
('NET-EN', 'Norethisterone enanthate'),
('NEW', 'Network of Empowered Women'),
('NFD', 'National Federation for Decency'),
('NFL', 'National Football League'),
('NFL', 'National Federation for Life'),
('NFP', 'Natural family planning'),
('NFPC', 'National Federation of PriestsCouncils'),
('NFPFA', 'Natural Family Planning Federation of America'),
('NFPRHA', 'National Family Planning and Reproductive Health Association'),
('NFS', 'National Fertility Study'),
('NGF', 'National Genetics Foundation'),
('NGHC', 'National Gay Health Coalition'),
('NGHEF', 'National Gay Health Education Foundation, Inc.'),
('NGLTF', 'National Gay and Lesbian Task Force'),
('NGO', 'Non-governmental organization'),
('NGU', 'Non-gonococcal urethritis'),
('NHANES', 'National Health and Nutrition Examination Survey'),
('NHI', 'National Health Insurance'),
('NHLA', 'National Hispanic Lawyers Association'),
('NHO', 'National Hospice Organization'),
('NHS', 'National Health Service'),
('NIAAA', 'National Institute of Alcohol Abuse and Alcoholism'),
('NIB', 'Nordic Investment Bank'),
('NIC', 'Newly industrializing country'),
('NICA', 'National Interfaith Coalition on Aging'),
('NICHD', 'National Institute of Child Health and Human Development'),
('NICM', 'National Institute for Campus Ministries'),
('NICU', 'Neonatal intensive care unit'),
('NIDA', 'National Institute on Drug Abuse'),
('NIE', 'Newly industrializing economy'),
('NIE', 'National Institute for Education'),
('NIEO', 'New International Economic Order'),
('NIH', 'National Institute of Health'),
('NIMBY', 'Not in my back yard'),
('NIMH', 'National Institute of Mental Health'),
('NINA', 'No Irish need apply'),
('NIRS', 'Nuclear Information Resource Service'),
('NLF', 'National Liberation Front'),
('NLFO', 'National Lesbian Feminist Organization'),
('NLG', 'National Lawyers Guild'),
('NLSY', 'National Longitudinal Survey of Youth'),
('NMA', 'National Medical Association'),
('NMR', 'Nuclear magnetic resonance [spectroscopy]'),
('NN', 'Nicaraguan Network'),
('NOAPP', 'National Organization on Adolescent Pregnancy and Parenting'),
('NOEL', 'National Organization of Episcopalians for Life'),
('NOLGS', 'National Organization of Lesbian and Gay Scientists'),
('NOLSW', 'National Organization of Legal Social Workers'),
('NON', 'National Organization of Non-Parents'),
('NOPARH', 'National Office of Post-Abortion Reconciliation and Healing'),
('NOPE', 'National Optimum Population Effort'),
('NORC', 'National Opinion Research Center'),
('NORCL', 'National Organization for the Repeal of Cocaine Laws'),
('NORD', 'National Organization for Rare Disorders'),
('NORML', 'National Organization for the Repeal of Marijuana Laws'),
('NPC', 'National Peoples Congress'),
('NPFC', 'National Pro-Family Coalition'),
('NPG', 'Negative Population Growth'),
('NPLD', 'National Pro-Life Democrats'),
('NPR', 'National Public Radio'),
('NRC', 'National Research Council'),
('NRCA', 'Natural Resources Council of America'),
('NRDA', 'Natural Resources Defense Association'),
('NRDC', 'National Resource Defense Council'),
('NRFF', 'National Research Foundation for Fertility'),
('NRHP', 'National Reproductive Health Project'),
('NRHRC', 'National Rehabilitation Hospital Research Center'),
('NRL-PAC', 'National Right to Life Political Action Committee'),
('NRLC', 'National Right to Life Committee'),
('NSC', 'National Security Council'),
('NSCE', 'National Center for Science Education'),
('NSF', 'National Science Foundation'),
('NSFG', 'National Survey of Family Growth'),
('NSG', 'Nuclear Suppliers Group'),
('NSGC', 'National Society of Genetic Counselors'),
('NSM', 'National Survey of Men'),
('NSNA', 'National Student Nurses Association'),
('NSTA', 'National Science Teachers Association'),
('NSW', 'New South Wales'),
('NT', 'New Testament'),
('NTD', 'Neural tube defect'),
('NTL', 'National Teens for Life'),
('NUL', 'National Urban League'),
('NWA', 'Niggers With Attitude'),
('NWCL', 'National Womens Coalition for Life'),
('NWF', 'National Wildlife Federation'),
('NWHN', 'National Womens Health Network'),
('NWLC', 'National Womens Law Center'),
('NWM', 'New Ways Ministry'),
('NWPC', 'National Womens Political Caucus'),
('NWRA', 'National Welfare Rights Association'),
('NWSC', 'National Womens Studies Conference'),
('NYA', 'National Youth Administration'),
('NYPLC', 'National Youth Pro-Life Coalition'),
('OAPEC', 'Organization of Arab Petroleum Exporting Countries'),
('OAPP', 'Office of Adolescent Pregnancy Programs [United States Department of'),
('HHS', 'Health and Human Services'),
('OAS', 'Organization of American States'),
('OAS', 'Organization of American States'),
('OAU', 'Organization of African Unity'),
('OC', 'Order of Cistercians'),
('OC', 'Oral contraceptive'),
('OCA', 'Orthodox Church of America'),
('OCarm', 'Order of Carmelites'),
('OCart', 'Order of Carthusians'),
('OCC', 'Order of Calced Carmelites'),
('OCD', 'Order of Discalced Carmelites'),
('OCI', 'Ovum capture inhibitor'),
('OCSO', 'Order of Cistercians of the Strict Observance'),
('ODC', 'Order of Discalced Carmelites'),
('OEA', 'Office of Environmental Affairs'),
('OECD', 'Organization for Economic Cooperation and Development'),
('OECD', 'Organization for Economic Cooperation and Development'),
('OECS', 'Organization of Eastern Caribbean States'),
('OEEC', 'Organization for European Economic Cooperation'),
('OEO', 'Office of Economic Opportunity'),
('OERI', 'Office of Educational Research and Improvement'),
('OES', 'Order of the Eastern Star'),
('OFM', 'Order of Friars Minor'),
('OGC', 'Office of General Council'),
('OI', 'Osteogenesis imperfecta'),
('OIC', 'Organization of the Islamic Conference'),
('OM', 'Ovulation method'),
('OMB', 'Office of Management and Budget'),
('OMI', 'Oblates of Mary Immaculate'),
('ONUSAL', 'United Nations Observer Mission in El Salvador'),
('oob', 'off our backs [Magazine]'),
('Op cit', 'Opere citato'),
('OP', 'Order of Preachers'),
('OP', 'Optimum Population, Inc.'),
('OPA', 'Organ Procurement Agency'),
('OPANAL', 'Organismo para la Proscripcion de las Armas Nucleares en la'),
('ALC', 'America Latina y el Caribe'),
('APNWLAC', 'Agency for the Prohibition of Nuclear Weapons in Latin America and the Caribbean'),
('OPEC', 'Organization of Petroleum Exporting Countries'),
('OPEC', 'Organization of Petroleum Exporting Countries'),
('OPEN', 'Organization to Promote Equality Now'),
('OPM', 'Office of Personnel Management'),
('OPR', 'Office of Population Research, Princeton University'),
('OR', 'Operation Rescue'),
('OSA', 'Order of St. Augustine'),
('OSB', 'Order of St. Benedict'),
('OSF', 'Order of St. Francis'),
('OSHA', 'Occupational Safety and Health Administration'),
('OSM', 'Order of the Servants of Mary'),
('OSU', 'Order of St. Ursula'),
('OSV', 'Our Sunday Visitor [Magazine]'),
('OT', 'Old Testament'),
('OT', 'Ovum transfer'),
('OT', 'Occupational therapy'),
('OTA', 'Office of Technology Assessment'),
('OTC', 'Over the counter'),
('OTGH', 'Old-Time Gospel Hour'),
('OURS', 'Organization for United Response'),
('P-FLAG', 'Parents and Friends of Lesbians and Gays'),
('P.C.', 'Politically correct'),
('P.R.', 'Public relations'),
('P-IUD', 'Progestagen-releasing intrauterine devices'),
('PA', 'Power of attorney'),
('PA', 'Physicians assistant'),
('PA', 'Public address'),
('PA', 'Prothonotary apostolic'),
('PA', 'Parents Anonymous'),
('PAA', 'Population Association [or Assistance] of America'),
('PAC', 'Political action committee'),
('PAC', 'Population Action Council'),
('PACE', 'Post-Abortion Counseling and Education'),
('PAF', 'Platelet-activating factor'),
('PAHO', 'Pan American Health Organization'),
('PAPOC', 'Parents Alliance to Protect Our Children'),
('PAPP-A', 'Pregnancy-associated plasma protein-A'),
('PAS', 'Post-abortion syndrome'),
('PATH', 'Post-Abortion Trauma Healing'),
('PATH', 'Program for Appropriate Technology in Health'),
('PAU', 'Pan American Union'),
('PAW', 'People for the American Way'),
('PBS', 'Public Broadcasting System'),
('PC', 'Personal computer'),
('PC', 'Population Communication'),
('PCA', 'Permanent Court of Arbitration'),
('PCA', 'Presbyterian Church in America'),
('PCC', 'Population Crisis [or Control] Committee'),
('PCI', 'Pax Christi International'),
('PCI', 'Population Communications International'),
('PCO', 'Polycystic ovary syndrome'),
('PCS', 'Population Communication Services, Johns Hopkins University'),
('PCUC', 'People Concerned for the Unborn Child'),
('PCUSA', 'Presbyterian Church of the USA'),
('PD', 'Peak day'),
('PDA', 'Population Development Association'),
('PDA', 'Pregnancy Disability Act'),
('PDQ', 'Pretty damn quick'),
('PDR', 'Physicians Desk Reference'),
('PDW', 'Peoples Daily World Magazine'),
('PEACE', 'People Expressing a Concern for Everyone'),
('PECAM', 'Platelet endothelial cell adhesion molecule'),
('PEI', 'Prince Edward Island'),
('PEN', '[International Association of] Poets, Playwrights, Editors, Essayists, and Novelists'),
('PEP', 'Promoting Enduring Peace'),
('PETA', 'People for the Ethical Treatment of Animals'),
('PFL', 'Prayer and Fasting League'),
('PG', 'Prostaglandin'),
('Ph.D.', 'Philosophiae doctor'),
('PHA', 'Public Housing Administration'),
('PHS', '[United States] Public Health Service'),
('PHWFL', 'Public Health Workers for Life'),
('PI', 'Pearl Index'),
('PI', 'Population Institute'),
('PI', 'Private investigator'),
('PID', 'Pelvic inflammatory disease'),
('PIE', 'Paedophiliac International Exchange'),
('PIH', 'Pyridoxal isonicotinoyl hydrazone'),
('PIP', 'Population Information Program, Johns Hopkins University'),
('PIRG', 'Public Interest Research Group'),
('PK', 'Psychokinesis'),
('PKU', 'Phenylketonuria'),
('PLAL', 'Pro-Life Action Network'),
('PLAL', 'Pro-Life Action League'),
('PLAN', 'Plan Loving Adoption Now'),
('PLAN', 'Protect Life in All Nations'),
('PLEA', 'Pro-Life Educational Association'),
('PLO', 'Palestinian Liberation Organization'),
('PMS', 'Pre-menstrual syndrome'),
('PNAP', 'Prolife Nonviolent Action Project'),
('PND', 'Prenatal diagnosis'),
('PO', 'Post office'),
('POC', 'Products of conception'),
('POC', 'Prisoners of conscience'),
('POM', 'Public opinion message'),
('POPTECH', 'Population Technical Assistance Project'),
('POSSLQ', 'Person of the opposite sex sharing living quarters'),
('POV', 'Point of View [television program]'),
('PP/WP', 'Planned Parenthood/World Population'),
('PP', 'Planned Parenthood'),
('PP5', 'Placental protein 5'),
('PPAF', 'Planned Parenthood Action Fund'),
('PPD', 'Purified protein derivative'),
('PPD', 'Post-partum depression'),
('PPFA', 'Planned Parenthood Federation of America'),
('PPFC', 'Planned Parenthood Federation of Canada'),
('PPIH', 'Population Planning and International Health'),
('PPL', 'Presbyterians Pro-Life'),
('PPNG', 'Penicillinase-producing Neisseria gonorrhea'),
('PPP', 'Planned Parenthood Physicians'),
('PPPPPPP', 'Proper prior planning prevents putrid poor performance'),
('PRB', 'Population Reference Bureau'),
('PRC', 'Peoples Republic of China'),
('PRC', 'Population Resource Center'),
('PRL', 'Prolactin'),
('PRM', 'Physicians for Moral Responsibility'),
('PRO', 'Public relations officer'),
('PRO', 'Population Renewal Office'),
('PRO', 'ParentsRights Organization'),
('ProPAC', 'Progressive Political Action Committee'),
('PROST', 'Pronuclear stage tubal transfer'),
('PS', 'Pro-Lifers for Survival'),
('PS', 'Postscriptum'),
('PSA', 'Public service announcement'),
('PSHA', 'Public Service Health Act'),
('PSI', 'Population Services International'),
('PSI', 'Population Services Institute'),
('PSR', 'Physicians for Social Responsibility'),
('PSS', 'Peace Science Society'),
('PST', 'Pacific Standard Time'),
('PSYOPS', 'Psychological operations'),
('PTA', 'Parent-Teacher Association'),
('PTSD', 'Post-traumatic stress disorder'),
('PUSH', 'People United to Save Humanity'),
('PVS', 'Persistent vegetative state'),
('PWA', 'Person with AIDS'),
('QALY', 'Quality adjusted life years'),
('QED', 'Quod erat demonstrandum'),
('QFB', 'Queers fight back'),
('QN', 'Queer Nation'),
('QOL', 'Quality of life'),
('QUEST', 'Queers Undertaking Exquisite and Symbolic Transformation'),
('R', '[Degrees] Rankin'),
('R&D', 'Research and development'),
('R2N2', 'Reproductive Rights National Network'),
('RAPID', 'Resources for the Awareness of Population Impacts on Development'),
('RATS', 'Radical [AIDS] Activist Truth Squad'),
('RC', 'Roman Catholic'),
('RCA', 'Reformed Church of America'),
('RCAR', 'ReligiousCoalition for Abortion Rights'),
('RCP', 'Revolutionary Communist Party [of the U.S.]'),
('RCP', 'Royal College of Physicians'),
('RCS', 'Royal College of Surgeons'),
('RD', 'Rural delivery'),
('RFC', 'Religious Formation Conference'),
('RFD', 'Rural free delivery'),
('RFRA', 'Religious Freedom Restoration Act'),
('RG', 'Rio Group'),
('RGC', 'Repository for Germinal Choice'),
('RH', 'Rhesus [positive or negative]'),
('RHLA', 'Respect Human Life Act'),
('RICO', 'Racketeering-Influenced Corrupt Organizations Act'),
('RIP', 'Requiescat in pace'),
('RM', 'Reichsmark'),
('RN', 'Registered nurse'),
('RNA', 'Ribonucleic acid'),
('RNC', 'Republican National Committee'),
('ROC', 'Republic of China'),
('ROK', 'Republic of Korea'),
('ROTC', 'Reserve Officers Training Corps'),
('RRC', 'Reproductive Rights Coalition'),
('RRN', 'Reproductive Rights Network'),
('RSCJ', 'Religious of the Sacred Heart of Jesus'),
('RSV', 'Revised standard version'),
('RTI', 'Research Triangle Institute'),
('RTL', 'Right to Life'),
('RTLC', 'Right to Life Crusade'),
('RU', 'Roussel-Uclaf'),
('RVN', 'Republic of Viet Nam'),
('RW', 'Revolutionary Worker Magazine'),
('RW', 'Renaissance Women'),
('s-T', 'sympto-thermal'),
('s&M', 'sado-masochism'),
('sA', 'sexaholics Anonymous'),
('sA', 'salvation Army'),
('sA', 'spontaneous abortion'),
('sAA', 'sexual Addicts Anonymous'),
('sAA', 'society for Applied Anthropology'),
('sAARC', 'south Asian Association for Regional Cooperation'),
('sAC', 'state Advisory Committee'),
('sACU', 'southern African Customs Union'),
('sADC', 'southern African Development Community'),
('sAIDS', 'simian Acquired Immune Deficiency Syndrome'),
('sALT', 'strategic Arms Limitation Talks'),
('sAM', 'society for Adolescent Medicine'),
('sAMA', 'student American Medical Association'),
('sAR', 'sexual attitude restructuring'),
('sART', 'society for Assisted Reproductive Technologies'),
('sAS', 'sisters Against Sexism'),
('sAT', 'scholastic Aptitude Test'),
('sB', 'senate Bill'),
('sBC', 'school-based clinic'),
('sC', 'sisters of Charity'),
('sCAW', 'scientists Center for Animal Welfare'),
('scD', 'Doctor of Science'),
('sCI-COP', 'Committee for the Scientific Investigation of Claims of the Paranormal'),
('sCLC', 'southern Christian Leadership Conference'),
('sCUM', 'society for Cutting Up Men'),
('sD', 'standard deviation'),
('sD', 'senile dementia'),
('sD', 'strategic Defense Development and Deployment'),
('sDAT', 'senile Dementia, Alzheimers Type'),
('sDC', 'social Development Center'),
('sDI', 'strategic Defense Initiative'),
('sDS', 'students for a Democratic Society'),
('sEAL', 'sea, Air, Land'),
('sELA', 'sistema Economico Latinoamericana'),
('sEM', 'scanning electron microscope'),
('sFRY', 'socialist Federal Republic of Yugoslavia'),
('sG', 'surgeon General'),
('sIDS', 'sudden Infant Death Syndrome'),
('sIECUS', 'sex Information and Education Council of the United States'),
('sIFT', 'sperm Intrafallopian Transfer'),
('sIG', 'special Interest Group'),
('sIGMA', 'sisters in Gay Ministry Associated'),
('sIM', 'simian Immunodeficiency Virus'),
('sJ', 'society of Jesus'),
('sJD', 'Doctor of Juridical Science'),
('sJR', 'senate Joint Resolution'),
('sKAT', 'sex Knowledge and Attitude Test'),
('sLAA', 'sex and Love Addicts Anonymous'),
('sLAPP', 'strategic lawsuit against public participation'),
('sLBM', 'submarine-Launched Ballistic Missiles'),
('sM', 'society of Mary'),
('sMP', 'social Marketing Project'),
('sMSA', 'standard Metropolitan Statistical Area'),
('sNAFU', 'situation normal'),
('sNCC', 'student Non-Violent Coordinating Committee'),
('sOMARC', 'social Marketing for Change'),
('sOP', 'standard operating procedure'),
('sOR', 'shield of Roses'),
('sOS', 'secular Organization for Sobriety Societies'),
('sOUL', 'save Our Unwanted Life'),
('sP1', 'Pregnancy-specific beta 1-glycoprotein'),
('sPA-TP', 'staphylococcal protein A-IgG'),
('sPARTECA', 'south Pacific Regional Trade and Economic Cooperation Agreement'),
('sPC', 'south Pacific Commission'),
('sPCA', 'society for the Prevention of Cruelty to Animals'),
('sPF', 'south Pacific Forum'),
('sPHA', 'solid-phase hemadsorption assay'),
('sPI', 'sisters of Perpetual Indulgence'),
('sPR', 'society for Psychical Research'),
('sPUC', 'society for the Protection of the Unborn Child'),
('sQUASH', 'super Queers United Against Savage Heterosexuals'),
('sRA', 'science Research Associates'),
('sRA', 'states Rights Amendment'),
('sRD', 'society for the Right to Die'),
('sRP', 'short rib-polydactyly syndrome'),
('sS', 'schutzstaffel'),
('sS', 'saints'),
('sSA', 'social Security Administration'),
('sSA', 'social Security Act'),
('sSSS', 'society for the Scientific Study of Sex'),
('sTART', 'strategic arms reduction treaty'),
('sTB', 'sacrae theologiae baccalaureus'),
('sTD', 'sexually-transmitted disease'),
('sTD', 'sacrae theologiae doctor'),
('sTL', 'sacrae theologiae licentiatae'),
('sTM', 'sacrae theologiae masterieus'),
('sTM', 'sympto-thermal method'),
('sTOP', 'save the Oppressed People'),
('sTOPP', 'stop Planned Parenthood'),
('sTP', 'standard temperature and pressure'),
('sUZI', 'sub-zonal insemination'),
('sV', 'soror Vitae'),
('sWAT', 'special Weapons and Tactics'),
('sWS', 'sociologists for Women in Society'),
('sYL', 'spartacus Youth League'),
('T.O.P.', '[Dominican] Third Order of Penance'),
('TA', 'Transabdominal'),
('TALL', 'Teen American Life League'),
('TANSTAAFL', 'There aint no such thing as a free lunch'),
('TARAL', 'Texas Abortion Rights Action League'),
('TARS', 'Thrombocytopenia with absent radii syndrome'),
('TAT', 'Tray agglutination test'),
('TBA', 'To be aborted'),
('TBA', 'To be announced'),
('TC', 'Transcervical'),
('TEF', 'The Environmental Fund'),
('TEGWAR', 'The exciting game without any rules'),
('TFR', 'Total fertility rate'),
('TFRI', 'Transnational Family Research Institute'),
('ThD', 'Doctor of Theology'),
('TIET', 'Transvaginal intratubal embryo transfer'),
('TIPPS', 'Technical Information Population for the Private Sector'),
('TLB', 'The Living Bank'),
('TLC', 'Tender loving care'),
('TLC', 'Teen Line Connection'),
('TLN', 'The Lavender Network Magazine'),
('TM', 'Transcendental meditation'),
('TOT', 'Tubal ovum transfer'),
('TOTS', 'Tubal ovum transfer of sperm'),
('TP', 'Treponema pallidum'),
('TRO', 'Temporary restraining order'),
('TRUTH', 'Teens Rescuing Unborn Tiny Humans'),
('TSC', 'Teachers Saving Children'),
('TSD', 'Tay-Sachs Disease'),
('TTAPS', 'Toon, Turco, Ackerman, Pollack, and Sagan'),
('TTET', 'Transvaginal-transmyometrial embryo transfer'),
('TV-TEST', 'Transvaginal tubal embryo stage transfer'),
('TVC', 'Traditional Values Coalition'),
('UAE', 'United Arab Emirates'),
('UAW', 'United Auto, Aircraft, and Agricultural Implements Workers of America'),
('UCC', 'United Church of Christ'),
('UCLA', 'University of California at Los Angeles'),
('UCS', 'Union of Concerned Scientists'),
('UDDA', 'Uniform Determination of Death Act'),
('UDEAC', 'Union Douaniere et Economique de lAfrique Centrale'),
('ACEU', 'African Customs and Economic Union'),
('UER', 'User effectiveness rate'),
('UFL', 'University Faculty for Life'),
('UFMCC', 'Universal Fellowship of Metropolitan Community Churches'),
('UMC', 'United Methodist Church'),
('UN', 'United Nations'),
('UNAVEM', 'United Nations Angola Verification Mission'),
('UNCTAD', 'United Nations Conference on Trade and Development'),
('UNDIESA', 'United Nations Department of International Economic and Social Affairs'),
('UNDOF', 'United Nations Disengagement Observer Force'),
('UNDP', 'United Nations Development Program'),
('UNDP', 'United Nations Development Program'),
('UNEP', 'United Nations Environment Program'),
('UNESCO', 'United Nations Educational, scientific, and Cultural Organization'),
('UNFAO', 'United Nations Food and Agricultural Organization'),
('UNFICYP', 'United Nations Force in Cyprus'),
('UNFPA', 'United Nations Fund for Population Activities'),
('UNHCR', 'United Nations Office of the High Commissioner for Refugees'),
('UNICEF', 'United Nations Childrens Emergency Fund'),
('UNIDO', 'United Nations International Development Organization'),
('UNIFEM', 'United Nations Development Fund for Women'),
('UNIFIL', 'United Nations Interim Force in Lebanon'),
('UNIKOM', 'United Nations Iraq-Kuwait Observation Mission'),
('UNMOGIP', 'United Nations Military Observer Group in India and Pakistan'),
('UNOMOZ', 'United Nations Operation in Mozambique'),
('UNOS', 'United Network for Organ Sharing'),
('UNOSOM', 'United Nations Operation in Somalia'),
('UNPROFOR', 'United Nations ProtectionForce'),
('UNRWA', 'United Nations Relief and Works Agency for Palestine Refugees in the'),
('NE', 'Near East'),
('UNTAC', 'United Nations Transitional Authority in Cambodia'),
('UNTSO', 'United Nations Truce Supervision Organization'),
('UPA', 'Unwed Parents Anonymous'),
('UPC', 'United Pro-Life Council'),
('UPI', 'United Press International'),
('UPS', 'Uterine progesterone system'),
('UPU', 'Universal Postal Union'),
('UPUSA', 'United Presbyterians USA'),
('URC', 'University Research Corporation'),
('USAF', 'United States Air Force'),
('USAID', 'United States Agency for International Development'),
('USCC', 'United States Catholic Conference'),
('USCL', 'United States Coalition for Life'),
('USCRC', 'United States Civil Rights Commission'),
('USCSC', 'United States Civil Service Commission'),
('USGPO', 'United States Government Printing Office'),
('USIA', 'United States Information Agency'),
('USMC', 'United States Marine Corps'),
('USPS', 'United States Postal Service'),
('USSR/EE', 'USSR/Eastern Europe'),
('USSR', 'Union of Soviet Socialist Republics'),
('UTI', 'Urinary tract infection'),
('UUA', 'Unitarian Universalist Association'),
('UWA', 'United Way of America'),
('VA', 'Veterans Administration'),
('VBAC', 'Vaginal birth after Cesarian [section]'),
('VD', 'Venereal disease'),
('VFC', 'Voters for Choice'),
('VFW', 'Veterans of Foreign Wars'),
('VHEMT', 'Voluntary Human Extinction Movement'),
('VIP', 'Voter identification project'),
('VIP', 'Voluntary interruption of pregnancy'),
('VITI', 'Vaginal intratubal insemination'),
('VOA', 'Voice of America'),
('VOC', 'Victims of Choice'),
('VOGUE', 'Valiant Out Gays United in Energy'),
('VP', 'Vice President'),
('VSC', 'Voluntary surgical contraception'),
('VVF', 'Vesico-vaginal fistula'),
('WAA', 'Womens Action Alliance'),
('WADB', 'West African Development Bank'),
('WAP', 'Whale Adoption Project'),
('WAP', 'Women Against Pornography'),
('WARN', 'Women of All Red Nations'),
('WASP', 'We Are Sexual Perverts'),
('WASP', 'We are Satans people'),
('WATS', 'Wide Area Telephone System'),
('WCC', 'World Council of Churches'),
('WCCL', 'Wisconsin Citizens Concerned for Life'),
('WCF', 'Womens Campaign Fund'),
('WCL', 'World Confederation of Labor'),
('WEAL', 'Womens Equity Action League'),
('WEBA', 'Women Exploited By Abortion'),
('WENCH', 'Women with Enough Nerve to Create Havoc'),
('WETSU', 'We eat this sh_t up'),
('WEU', 'Western European Union'),
('WFAVS', 'World Federation of Associations for Voluntary Sterilization'),
('WFC', 'World Food Council'),
('WFF', 'Women for Faith and Family'),
('WFP', 'World Food Program'),
('WFP', 'Witness for Peace'),
('WFS', 'World Fertility Survey'),
('WFTU', 'World Federation of Trade Unions'),
('WHAM', 'Womens Health Action Mobilization'),
('WHCA', 'White House Conference on Aging'),
('WHCCY', 'White House Conference on Children and Youth'),
('WHCF', 'White House Conference on Families'),
('WHCH', 'White House Conference on Hunger'),
('WHO', 'World Health Organization'),
('WHO', 'World Health Organization'),
('WIC', 'Womens International Conference'),
('WIC', 'Women, Infants and Children Program'),
('WICCA', 'Women in Constant Creative Action'),
('WILPF', 'Womens International League for Peace and Freedom'),
('WIPO', 'World Intellectual Property Organization'),
('WISC', 'Washington Interreligious Staff Council'),
('WITCH', 'Witches International Conspiracy from Hell'),
('WLDF', 'Womens Legal Defense Fund'),
('WLF', 'Washington Legal Foundation'),
('WLNC', 'Womens Leadership Network Conference'),
('WMA', 'World Medical Association'),
('WMA', 'Womens Medical Association'),
('WMO', 'World Meteorological Organization'),
('WNAAC', 'Womens National Abortion Action Coalition'),
('WNDC', 'Womens National Democratic Club'),
('WOC', 'Womens Ordination Conference'),
('WOMB', 'Women Opposed to Massacre and Brutality'),
('WOOMB', 'World Organization of the Ovulation Method Billings'),
('WP', 'Warsaw Pact'),
('WPC', 'World Population Council'),
('WPS', 'World Population Society'),
('WRA', 'Women of reproductive age'),
('WRAP', 'White Ribbon Campaign Against Pornography'),
('WRI', 'World Resources Institute'),
('WSP', 'Women Strike for Peace'),
('WTO', 'World Tourism Organization'),
('WVSC', 'Water vacuum suction curettage'),
('WWF', 'World Wildlife Fund'),
('WWI', 'Worldwatch Institute'),
('Xn', 'Christian'),
('YAF', 'Young Americans for Freedom'),
('YAF', 'Young America Foundation'),
('YCL', 'Young Communist League'),
('YMCA', 'Young Mens Christian Association'),
('YWCA', 'Young Womens Christian Association'),
('ZACE', 'Zoapatle aqueous crude extract'),
('ZC', 'Zangger Committee'),
('ZDV', 'Zidovudine'),
('ZIFT', 'Zygote intra-fallopian transfer'),
('ZOG', 'Zionist Occupation Government'),
('ZPG', 'Zero Population Growth');
